apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: lzhaxydly-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/lzhaxydly-dotnet-basic-gitops